services:
    monochrome:
        build: .
        container_name: monochrome
        restart: unless-stopped
        networks:
            - proxy
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.monochrome.rule=Host(`monochrome.zpl.ovh`)'
            - 'traefik.http.routers.monochrome.entrypoints=websecure'
            - 'traefik.http.routers.monochrome.tls.certresolver=myresolver'
            - 'traefik.http.services.monochrome.loadbalancer.server.port=4173'

networks:
    proxy:
        external: true
